import {createStore} from "vuex";
import axios from "@/utils/axios.js";
import img1AccBg from '@/assets/img/ourAccomplishments/first-bg.png';
import img1Acc from '@/assets/img/ourAccomplishments/11.jpg'
import img2Acc from '@/assets/img/ourAccomplishments/22.jpg'
import img3Acc from '@/assets/img/ourAccomplishments/33.png'
import img1 from '@/assets/img/insights/kazMunaiGaz.png'
import imgInds1 from "@/assets/img/indSectors/1.jpg";
import imgInds2 from "@/assets/img/indSectors/2.jpg";
import imgInds3 from "@/assets/img/indSectors/3.jpg";
import imgInds4 from "@/assets/img/indSectors/4.jpg";
import imgProd1 from '@/assets/img/products/first.png'
import imgProd2 from '@/assets/img/products/second.png'
import imgProd3 from '@/assets/img/products/third.png'
import imgProd4 from '@/assets/img/products/fourth.png'
import acc1 from "@/assets/pdfs/1.pdf"
import prodPDF1 from "@/assets/pdfs/1.pdf"
import prodPDF2 from "@/assets/pdfs/2.pdf"
import prodPDF3 from "@/assets/pdfs/3.pdf"
import prodPDF4 from "@/assets/pdfs/4.pdf"
import part1 from '@/assets/img/partners/1.png'
import part2 from '@/assets/img/partners/2.png'
import part3 from '@/assets/img/partners/3.png'
import part4 from '@/assets/img/partners/4.png'
import part5 from '@/assets/img/partners/5.png'
import part6 from '@/assets/img/partners/6.png'
import part7 from '@/assets/img/partners/7.png'
import part8 from '@/assets/img/partners/8.png'
import part9 from '@/assets/img/partners/9.png'
import part10 from '@/assets/img/partners/10.png'
import part11 from '@/assets/img/partners/11.png'
import part12 from '@/assets/img/partners/12.png'
import part13 from '@/assets/img/partners/13.png'

export default createStore({
    modules: {}, actions: {
        async sendMessage({commit}) {
            const {data} = await axios.post("/branches/all", form);
            commit("updateBranchesList", data);

        }
    }, mutations: {}, state: {
        news: [{
            id: 1,
            title: "АСКОУ – ПРОЕКТ ИНВЕНТАРИЗАЦИИ В АО НК «КАЗМУНАЙГАЗ»",
            title_kz: "ASKOU – «ҚАЗМҰНАЙГАЗ» ҰК» АҚ ТҮҚМАЛДЫҚ ЖОБАСЫ",
            title_en: "ASKOU – INVENTORY PROJECT IN JSC NC KAZMUNAYGAS",
            img: img1,
            short_desc: "Национальной компанией «КазМунайГаз» в рамках цифровизации в 2020 году была внедрена система автоматизированного учета основных средств «АСКОУ – Инвентаризация».",
            short_desc_kz: "«ҚазМұнайГаз» ұлттық компаниясы 2020 жылы «АСКОУ – Инвентаризация» негізгі бөлімдерінің автоматтандырылған жүйесіне негізделген.",
            short_desc_en: "The national company \"KazMunayGas\" as part of digitalization in 2020 introduced an automated accounting system for fixed assets \"ASKOU - Inventory\".",
            description: "Национальная компания «КазМунайГаз» в рамках цифровизации в 2020 году внедрила систему автоматизированного учета основных средств «АСКОУ – Инвентаризация». Работа выполнялась «под ключ», включая поставку оборудования, обучение пользователей и бесплатное обслуживание в первый год использования. Все основные средства на балансе АО НК «КазМунайГаз» были оцифрованы RFID-метками различного назначения, проведен внешний осмотр и фотографировано текущее состояние ОС, все данные сохранены в системе. В системе также была создана организационная структура предприятия, введены сотрудники и пользователи основных средств, разграничены права пользователей согласно матрице полномочий. Система АСКОУ – Инвентаризация сократит время инвентаризации в несколько раз, привлекая при этом минимум сотрудников, минимизирует влияние человеческого фактора на результаты инвентаризации, автоматизирует контроль за всеми финансово ответственными лицами/пользователями ОС. Для удобства использования реализована интеграция с ERP-системой предприятия – SAP и с Active Directory.",
            description_kz: "«ҚазМұнайГаз» ұлттық компаниясы цифрландыру аясында 2020 жылы «ASKOU – Inventory» негізгі құралдарды автоматтандырылған есепке алу жүйесін енгізді. Жұмыс «кілтпен» орындалды, оның ішінде жабдықты жеткізу, пайдаланушыларды оқыту және пайдаланудың бірінші жылында тегін техникалық қызмет көрсету. «ҚазМұнайГаз» ҰК АҚ теңгеріміндегі барлық негізгі құралдар әртүрлі мақсаттағы RFID белгілерімен цифрландырылды, сыртқы тексеру жүргізілді және ОЖ-ның ағымдағы жағдайы суретке түсірілді, барлық деректер жүйеде сақталды. Жүйеде кәсіпорынның ұйымдық құрылымы да құрылды, жұмыскерлер мен негізгі құралдарды пайдаланушылар енгізілді, өкілеттік матрицасы бойынша пайдаланушы құқықтары шектелді. ASKOU – Түгендеу жүйесі ең аз қызметкерлерді тарта отырып, түгендеу уақытын бірнеше есе қысқартады, түгендеу нәтижелеріне адам факторының әсерін барынша азайтады, барлық қаржылық жауапты тұлғаларды/ОЖ пайдаланушыларын бақылауды автоматтандырады. Пайдаланудың қарапайымдылығы үшін Enterprise ERP жүйесімен - SAP және Active Directory-мен интеграция жүзеге асырылады.",
            description_en: "The national company \"KazMunayGas\" within the framework of digitalization in 2020 introduced the system of automated accounting of fixed assets \"ASKOU – Inventory\". The work was done \"turnkey\", including the supply of equipment, user training and free maintenance in the first year of use. All fixed assets on the balance sheet of JSC NC KazMunayGas were digitized with RFID tags for various purposes, an external inspection was carried out and the current state of the OS was photographed, all data was stored in the system. The organizational structure of the enterprise was also created in the system, employees and users of fixed assets were introduced, user rights were delimited according to the authority matrix. The ASKOU – Inventory system will reduce the time of inventory several times, while involving a minimum of employees, minimizes the impact of the human factor on the results of inventory, automates control over all financially responsible persons / OS users. For ease of use, integration with the Enterprise ERP system - SAP and with Active Directory is implemented.",
            certificates: [{
                id: 1,
                name: "Printed version of the news",
                name_kz: "Жаңалықтың баспа нұсқасы",
                name_en: "Печатная версия новости",
                file: acc1
            }]
        }], accomplishments: [{
            id: 1,
            title: "«КазАэронавигация» (США, Орландо, 2018) RFID Journal Live ЛУЧШЕЕ ВНЕДРЕНИЕ RFID-ТЕХНОЛОГИИ",
            title_kz: "«ҚазАэронавигация» (АҚШ, Орландо, 2018 ж.) RFID Journal Live RFID ТЕХНОЛОГИЯСЫНЫҢ ҮЗДІК ЕНГІЗУІ",
            title_en: "\"KazAeronavigation\" (USA, Orlando, 2018) RFID Journal Live BEST IMPLEMENTATION OF RFID TECHNOLOGY ",
            img: img1Acc,
            img_bg: img1AccBg,
            short_desc: "",
            short_desc_kz: "",
            short_desc_en: "",
            description: "",
            description_kz: "",
            description_en: "",
            certificates: [{
                id: 1,
                name: "Свидетельство, удостоверяющее регистрацию лица в качестве участника специальной экономической зоны",
                name_kz: "Тұлғаның арнайы экономикалық аймаққа қатысушы ретінде тіркелгенін куәландыратын куәлік",
                name_en: "Certificate certifying the registration of a person as a participant in a special economic zone",
                file: acc1
            }]
        }, {
            id: 2,
            title: "«КазМунайГаз» (США Лас-Вегас 2022) RFID Journal Live ЛУЧШЕЕ ВНЕДРЕНИЕ RFID-ТЕХНОЛОГИИ",
            title_kz: "«ҚазМұнайГаз» (АҚШ Лас-Вегас 2022) RFID журналы тікелей эфирде RFID ТЕХНОЛОГИЯСЫНЫҢ ҮЗДІК ЖАСАУЫ",
            title_en: "\"KazMunayGas\" (USA Las Vegas 2022) RFID Journal Live BEST IMPLEMENTATION OF RFID TECHNOLOGY \n",
            img: img2Acc,
            img_bg: img1AccBg,
            short_desc: "",
            short_desc_kz: "",
            short_desc_en: "",
            description: "",
            description_kz: "",
            description_en: "",
            certificates: [{
                id: 1,
                name: "Свидетельство, удостоверяющее регистрацию лица в качестве участника специальной экономической зоны",
                name_kz: "Тұлғаның арнайы экономикалық аймаққа қатысушы ретінде тіркелгенін куәландыратын куәлік",
                name_en: "Certificate certifying the registration of a person as a participant in a special economic zone",
                file: acc1
            }]
        }, {
            id: 3,
            title: "ТОП-4 ИННОВАЦИОННЫХ КОМПАНИЙ КАЗАХСТАНА",
            title_kz: "ҚАЗАҚСТАНДАҒЫ ТОП 4 ИННОВАЦИЯЛЫҚ КОМПАНИЯЛАР",
            title_en: "TOP 4 INNOVATIVE COMPANIES IN KAZAKHSTAN",
            img: img3Acc,
            img_bg: img1AccBg,
            short_desc: "",
            short_desc_kz: "",
            short_desc_en: "",
            description: "",
            description_kz: "",
            description_en: "",
            certificates: [{
                id: 1,
                name: "Свидетельство, удостоверяющее регистрацию лица в качестве участника специальной экономической зоны",
                name_kz: "Тұлғаның арнайы экономикалық аймаққа қатысушы ретінде тіркелгенін куәландыратын куәлік",
                name_en: "Certificate certifying the registration of a person as a participant in a special economic zone",
                file: acc1
            }]
        }, {
            id: 4,
            title: "Asia-Pacific, Asialaw Profiles 2021",
            title_kz: "Asia-Pacific, Asialaw Profiles 2021",
            title_en: "Asia-Pacific, Asialaw Profiles 2021",
            img: img3Acc,
            img_bg: img1AccBg,
            short_desc: "Команда GRATA International вошла в число лучших фирм Казахстана и заняла высшие позиции - выдающиеся и рекомендованные в области общего коммерческого права, энергетики, нефти и газа, строительства.",
            short_desc_kz: "GRATA International командасы Қазақстандағы ең жақсы фирмалардың қатарына қосылды және ең жоғары деңгейге қойылды - жалпы бизнес құқығы, энергетика, мұнай және газ, құрылыс саласында үздік және ұсынылды.",
            short_desc_en: "The team of GRATA International was ranked among the best firms in Kazakhstan and placed in the highest tiers - outstanding and recommended in General Business Law, Energy, Oil&Gas, Construction",
            description: "ABiTech заняла 4-е место в рейтинге «Топ-10 инновационных компаний Казахстана 2018»... по версии Национального агентства по\n" + "Технологического развития совместно с Бизнес-инкубатором МОСТ при поддержке Министерства по инвестициям и развитию РК проведен «Рэнкинг инновационных компаний Казахстана 2018». Принять участие могла любая казахстанская компания. ТОП-10 компаний-победителей были выбраны по результатам оценки независимых экспертов и технологической оценки АО «НАТР». Успехи ABiTech во внедрении инноваций в различных отраслях промышленности отмечены Дипломом и присвоено 4 место в рейтинге инновационных компаний Республики Казахстан.",
            description_kz: "ABiTech 2018 жылғы Қазақстанның үздік 10 инновациялық компаниясының рейтингінде 4-ші орынды иеленді…\n" + "Технологиялық даму, MOST бизнес-инкубаторымен бірлесіп, Қазақстан Республикасы Инвестициялар және даму министрлігінің қолдауымен «Қазақстанның инновациялық компанияларының рейтингі-2018» өткізілді. Кез келген қазақстандық компания қатыса алады. ТОП 10 жеңімпаз компания тәуелсіз сарапшылардың бағалауы мен «NATR» АҚ технологиялық бағалауының нәтижелері бойынша таңдалды. ABiTech компаниясының әртүрлі салаларға инновацияларды енгізудегі жетістігі Дипломмен марапатталып, Қазақстан Республикасындағы инновациялық компаниялардың рейтингінде 4-орынға ие болды.",
            description_en: "ABiTech is ranked 4th in the Top 10 Innovative Companies Ranking of Kazakhstan 2018… by the National Agency for\nTechnological Development, together with the MOST Business Incubator, with the support of the Ministry for Investment and Development of the Republic of Kazakhstan, the “Ranking of Innovative Companies of Kazakhstan 2018” was held. Any Kazakh company could take part. The TOP 10 Winning Companies were selected based on the results of an assessment by independent experts and a technological assessment by NATR JSC. The success of ABiTech in introducing innovations in various industries was awarded with a Diploma and was awarded the 4th place in the rating of innovative companies in the Republic of Kazakhstan.",
            certificates: [{
                id: 1,
                name: "Свидетельство, удостоверяющее регистрацию лица в качестве участника специальной экономической зоны",
                name_kz: "Тұлғаның арнайы экономикалық аймаққа қатысушы ретінде тіркелгенін куәландыратын куәлік",
                name_en: "Certificate certifying the registration of a person as a participant in a special economic zone",
                file: acc1
            }]
        }, {
            id: 5,
            title: "Asia-Pacific, Asialaw Profiles 2021",
            title_kz: "Asia-Pacific, Asialaw Profiles 2021",
            title_en: "Asia-Pacific, Asialaw Profiles 2021",
            img: img3Acc,
            img_bg: img1AccBg,
            short_desc: "Команда GRATA International вошла в число лучших фирм Казахстана и заняла высшие позиции - выдающиеся и рекомендованные в области общего коммерческого права, энергетики, нефти и газа, строительства.",
            short_desc_kz: "GRATA International командасы Қазақстандағы ең жақсы фирмалардың қатарына қосылды және ең жоғары деңгейге қойылды - жалпы бизнес құқығы, энергетика, мұнай және газ, құрылыс саласында үздік және ұсынылды.",
            short_desc_en: "The team of GRATA International was ranked among the best firms in Kazakhstan and placed in the highest tiers - outstanding and recommended in General Business Law, Energy, Oil&Gas, Construction",
            description: "ABiTech заняла 4-е место в рейтинге «Топ-10 инновационных компаний Казахстана 2018»... по версии Национального агентства по\n" + "Технологического развития совместно с Бизнес-инкубатором МОСТ при поддержке Министерства по инвестициям и развитию РК проведен «Рэнкинг инновационных компаний Казахстана 2018». Принять участие могла любая казахстанская компания. ТОП-10 компаний-победителей были выбраны по результатам оценки независимых экспертов и технологической оценки АО «НАТР». Успехи ABiTech во внедрении инноваций в различных отраслях промышленности отмечены Дипломом и присвоено 4 место в рейтинге инновационных компаний Республики Казахстан.",
            description_kz: "ABiTech 2018 жылғы Қазақстанның үздік 10 инновациялық компаниясының рейтингінде 4-ші орынды иеленді…\n" + "Технологиялық даму, MOST бизнес-инкубаторымен бірлесіп, Қазақстан Республикасы Инвестициялар және даму министрлігінің қолдауымен «Қазақстанның инновациялық компанияларының рейтингі-2018» өткізілді. Кез келген қазақстандық компания қатыса алады. ТОП 10 жеңімпаз компания тәуелсіз сарапшылардың бағалауы мен «NATR» АҚ технологиялық бағалауының нәтижелері бойынша таңдалды. ABiTech компаниясының әртүрлі салаларға инновацияларды енгізудегі жетістігі Дипломмен марапатталып, Қазақстан Республикасындағы инновациялық компаниялардың рейтингінде 4-орынға ие болды.",
            description_en: "ABiTech is ranked 4th in the Top 10 Innovative Companies Ranking of Kazakhstan 2018… by the National Agency for\nTechnological Development, together with the MOST Business Incubator, with the support of the Ministry for Investment and Development of the Republic of Kazakhstan, the “Ranking of Innovative Companies of Kazakhstan 2018” was held. Any Kazakh company could take part. The TOP 10 Winning Companies were selected based on the results of an assessment by independent experts and a technological assessment by NATR JSC. The success of ABiTech in introducing innovations in various industries was awarded with a Diploma and was awarded the 4th place in the rating of innovative companies in the Republic of Kazakhstan.",
            certificates: [{
                id: 1,
                name: "Свидетельство, удостоверяющее регистрацию лица в качестве участника специальной экономической зоны",
                name_kz: "Тұлғаның арнайы экономикалық аймаққа қатысушы ретінде тіркелгенін куәландыратын куәлік",
                name_en: "Certificate certifying the registration of a person as a participant in a special economic zone",
                file: acc1
            }]
        }, {
            id: 6,
            title: "Asia-Pacific, Asialaw Profiles 2021",
            title_kz: "Asia-Pacific, Asialaw Profiles 2021",
            title_en: "Asia-Pacific, Asialaw Profiles 2021",
            img: img3Acc,
            img_bg: img1AccBg,
            short_desc: "Команда GRATA International вошла в число лучших фирм Казахстана и заняла высшие позиции - выдающиеся и рекомендованные в области общего коммерческого права, энергетики, нефти и газа, строительства.",
            short_desc_kz: "GRATA International командасы Қазақстандағы ең жақсы фирмалардың қатарына қосылды және ең жоғары деңгейге қойылды - жалпы бизнес құқығы, энергетика, мұнай және газ, құрылыс саласында үздік және ұсынылды.",
            short_desc_en: "The team of GRATA International was ranked among the best firms in Kazakhstan and placed in the highest tiers - outstanding and recommended in General Business Law, Energy, Oil&Gas, Construction",
            description: "ABiTech заняла 4-е место в рейтинге «Топ-10 инновационных компаний Казахстана 2018»... по версии Национального агентства по\n" + "Технологического развития совместно с Бизнес-инкубатором МОСТ при поддержке Министерства по инвестициям и развитию РК проведен «Рэнкинг инновационных компаний Казахстана 2018». Принять участие могла любая казахстанская компания. ТОП-10 компаний-победителей были выбраны по результатам оценки независимых экспертов и технологической оценки АО «НАТР». Успехи ABiTech во внедрении инноваций в различных отраслях промышленности отмечены Дипломом и присвоено 4 место в рейтинге инновационных компаний Республики Казахстан.",
            description_kz: "ABiTech 2018 жылғы Қазақстанның үздік 10 инновациялық компаниясының рейтингінде 4-ші орынды иеленді…\n" + "Технологиялық даму, MOST бизнес-инкубаторымен бірлесіп, Қазақстан Республикасы Инвестициялар және даму министрлігінің қолдауымен «Қазақстанның инновациялық компанияларының рейтингі-2018» өткізілді. Кез келген қазақстандық компания қатыса алады. ТОП 10 жеңімпаз компания тәуелсіз сарапшылардың бағалауы мен «NATR» АҚ технологиялық бағалауының нәтижелері бойынша таңдалды. ABiTech компаниясының әртүрлі салаларға инновацияларды енгізудегі жетістігі Дипломмен марапатталып, Қазақстан Республикасындағы инновациялық компаниялардың рейтингінде 4-орынға ие болды.",
            description_en: "ABiTech is ranked 4th in the Top 10 Innovative Companies Ranking of Kazakhstan 2018… by the National Agency for\nTechnological Development, together with the MOST Business Incubator, with the support of the Ministry for Investment and Development of the Republic of Kazakhstan, the “Ranking of Innovative Companies of Kazakhstan 2018” was held. Any Kazakh company could take part. The TOP 10 Winning Companies were selected based on the results of an assessment by independent experts and a technological assessment by NATR JSC. The success of ABiTech in introducing innovations in various industries was awarded with a Diploma and was awarded the 4th place in the rating of innovative companies in the Republic of Kazakhstan.",
            certificates: [{
                id: 1,
                name: "Свидетельство, удостоверяющее регистрацию лица в качестве участника специальной экономической зоны",
                name_kz: "Тұлғаның арнайы экономикалық аймаққа қатысушы ретінде тіркелгенін куәландыратын куәлік",
                name_en: "Certificate certifying the registration of a person as a participant in a special economic zone",
                file: acc1
            }]
        }], indSectors: [{
            id: 1,
            title: "Нефть & Газ",
            title_kz: "Мұнай & газ",
            title_en: "Oil & Gas",
            description: "Технология RFID нашла ценное применение в нефтегазовой промышленности. Оно обеспечивает отслеживание и управление активами в режиме реального времени, от оборудования до персонала, улучшая протоколы безопасности и процедуры реагирования на чрезвычайные ситуации. Кроме того, RFID помогает в управлении запасами, логистике цепочки поставок, мониторинге окружающей среды и соблюдении нормативных требований. Он играет решающую роль в мониторинге состояния трубопроводов, обеспечении технического обслуживания оборудования и повышении безопасности посредством контроля доступа. Более того, системы RFID облегчают регистрацию данных и отчетность, повышая эффективность и соответствие отраслевым стандартам. Несмотря на многочисленные преимущества, успешное внедрение технологии RFID требует тщательного планирования и постоянного управления.",
            description_kz: "RFID технологиясы мұнай-газ саласында құнды қолданбаларды тапты. Ол жабдықтан бастап персоналға дейін активтерді нақты уақыт режимінде бақылауға және басқаруға, қауіпсіздік хаттамалары мен төтенше жағдайларға әрекет ету процедураларын жақсартуға мүмкіндік береді. Сонымен қатар, RFID инвентарлық қорларды басқаруға, жеткізу тізбегін логистикаға, қоршаған ортаны бақылауға және нормативтік талаптарға сәйкестікке көмектеседі. Ол құбыр жағдайларын бақылауда, жабдыққа техникалық қызмет көрсетуді қамтамасыз етуде және қол жеткізуді басқару арқылы қауіпсіздікті күшейтуде шешуші рөл атқарады. Сонымен қатар, RFID жүйелері тиімділікті арттыру және салалық стандарттарға сәйкестік үшін деректерді тіркеуді және есептілікті жеңілдетеді. Көптеген артықшылықтарына қарамастан, RFID технологиясын сәтті енгізу мұқият жоспарлауды және тұрақты басқаруды талап етеді.",
            description_en: "RFID technology has found valuable applications in the oil and gas industry. It enables real-time tracking and management of assets, from equipment to personnel, enhancing safety protocols and emergency response procedures. Additionally, RFID aids in inventory management, supply chain logistics, environmental monitoring, and regulatory compliance. It plays a crucial role in monitoring pipeline conditions, ensuring equipment maintenance, and bolstering security through access control. Moreover, RFID systems facilitate data logging and reporting for improved efficiency and compliance with industry standards. Despite its numerous benefits, successful implementation of RFID technology requires careful planning and ongoing management.",
            img: imgInds1,
            content: '<p class="mb-5">Технология RFID нашла ценное применение в нефтегазовой отрасли. Оно обеспечивает отслеживание и управление активами в режиме реального времени, от оборудования до персонала, улучшая протоколы безопасности и процедуры реагирования на чрезвычайные ситуации. Кроме того, RFID помогает в управлении запасами, логистике цепочки поставок, мониторинге окружающей среды и соблюдении нормативных требований. Он играет решающую роль в мониторинге состояния трубопроводов, обеспечении технического обслуживания оборудования и повышении безопасности посредством контроля доступа. Более того, системы RFID облегчают регистрацию данных и отчетность, повышая эффективность и соответствие отраслевым стандартам. Несмотря на многочисленные преимущества, успешное внедрение технологии RFID требует тщательного планирования и постоянного управления.</p>',
            content_kz: '<p class="mb-5">RFID технологиясы мұнай-газ саласында құнды қолданбаларды тапты. Ол жабдықтан персоналға дейін активтерді нақты уақыт режимінде бақылауға және басқаруға, қауіпсіздік хаттамалары мен төтенше жағдайларға әрекет ету процедураларын жақсартуға мүмкіндік береді. Сонымен қатар, RFID инвентарлық қорларды басқаруға, жеткізу тізбегін логистикаға, қоршаған ортаны бақылауға және нормативтік талаптарға сәйкестікке көмектеседі. Ол құбыр жағдайларын бақылауда, жабдыққа техникалық қызмет көрсетуді қамтамасыз етуде және қол жеткізуді басқару арқылы қауіпсіздікті күшейтуде шешуші рөл атқарады. Сонымен қатар, RFID жүйелері тиімділікті арттыру және салалық стандарттарға сәйкестік үшін деректерді тіркеуді және есептілікті жеңілдетеді. Көптеген артықшылықтарына қарамастан, RFID технологиясын сәтті енгізу мұқият жоспарлауды және үздіксіз басқаруды қажет етеді.</p>',
            content_en: '<p class="mb-5">RFID technology has found valuable applications in the oil and gas industry. It enables real-time tracking and management of assets, from equipment to personnel, enhancing safety protocols and emergency response procedures. Additionally, RFID aids in inventory management, supply chain logistics, environmental monitoring, and regulatory compliance. It plays a crucial role in monitoring pipeline conditions, ensuring equipment maintenance, and bolstering security through access control. Moreover, RFID systems facilitate data logging and reporting for improved efficiency and compliance with industry standards. Despite its numerous benefits, successful implementation of RFID technology requires careful planning and ongoing management.</p>',
            works: [part1, part4]
        }, {
            id: 2,
            title: "Горнодобывающая промышленность (клиенты АГМК)",
            title_kz: "Тау-кен (AGMK клиенттері)",
            title_en: "Mining  (clients AGMK)",
            description: "Технология RFID произвела революцию в горнодобывающей промышленности. Используя RFID-метки, компании могут эффективно отслеживать и управлять широким спектром активов, включая оборудование, инструменты и транспортные средства, гарантируя, что их местоположение и статус будут известны в режиме реального времени. Эта технология также упрощает управление запасами, особенно запасными частями и расходными материалами. Персонал может быть оснащен бейджами RFID, позволяющими точно отслеживать местоположение на горнодобывающих объектах, что повышает меры безопасности и возможности реагирования на чрезвычайные ситуации. RFID играет жизненно важную роль в цепочке поставок и логистике, регулируя движение материалов от добычи до переработки. Он также играет важную роль в планировании технического обслуживания и проверок, гарантируя соответствие оборудования стандартам безопасности. Внедрение RFID требует стратегического планирования и постоянного управления, но его преимущества с точки зрения безопасности, эффективности и соблюдения требований неоценимы для горнодобывающей промышленности.",
            description_kz: "RFID технологиясы тау-кен өнеркәсібіндегі операцияларда төңкеріс жасады. RFID тегтерін қолдану арқылы компаниялар активтердің кең ауқымын, соның ішінде жабдықтарды, құралдарды және көліктерді тиімді бақылап, басқара алады, олардың орны мен күйі нақты уақытта белгілі болуын қамтамасыз етеді. Бұл технология сонымен қатар инвентарлық қорларды, әсіресе қосалқы бөлшектер мен шығын материалдарын басқаруды жеңілдетеді. Персонал RFID бейджиктерімен жабдықталуы мүмкін, бұл тау-кен өндірісі объектілерінде орналасқан жерді дәл бақылауға мүмкіндік береді, бұл қауіпсіздік шаралары мен төтенше жағдайларды жою мүмкіндіктерін арттырады. RFID жеткізу тізбегі мен логистикада маңызды рөл атқарады, материалдардың өндіруден өңдеуге дейінгі қозғалысын реттейді. Ол сондай-ақ техникалық қызмет көрсету мен тексерулерді жоспарлауда маңызды рөл атқарады, жабдықтың қауіпсіздік стандарттарына сәйкестігіне кепілдік береді. RFID енгізу стратегиялық жоспарлауды және тұрақты басқаруды талап етеді, бірақ оның қауіпсіздік, тиімділік және сәйкестік бойынша артықшылықтары тау-кен өнеркәсібі үшін баға жетпес құнды болып табылады.",
            description_en: "RFID technology has revolutionized operations in the mining industry. By employing RFID tags, companies can effectively track and manage a wide array of assets, including equipment, tools, and vehicles, ensuring their location and status are known in real-time. This technology also streamlines inventory management, particularly for spare parts and consumables. Personnel can be equipped with RFID badges, enabling precise location tracking within mining facilities, which enhances safety measures and emergency response capabilities. RFID plays a vital role in supply chain and logistics, regulating the movement of materials from extraction to processing. It is also instrumental in scheduling maintenance and inspections, guaranteeing equipment compliance with safety standards. Implementing RFID requires strategic planning and ongoing management, but its benefits in terms of safety, efficiency, and compliance are invaluable to the mining industry.",
            img: imgInds2,
            content: '<p class="mb-5">Технология RFID произвела революцию в горнодобывающей промышленности. Используя RFID-метки, компании могут эффективно отслеживать и управлять широким спектром активов, включая оборудование, инструменты и транспортные средства, гарантируя, что их местоположение и статус будут известны в режиме реального времени. Эта технология также упрощает управление запасами, особенно запасными частями и расходными материалами. Персонал может быть оснащен бейджами RFID, позволяющими точно отслеживать местоположение на горнодобывающих объектах, что повышает меры безопасности и возможности реагирования на чрезвычайные ситуации. RFID играет жизненно важную роль в цепочке поставок и логистике, регулируя движение материалов от добычи до переработки. Он также играет важную роль в планировании технического обслуживания и проверок, гарантируя соответствие оборудования стандартам безопасности. Внедрение RFID требует стратегического планирования и постоянного управления, но его преимущества с точки зрения безопасности, эффективности и соблюдения требований неоценимы для горнодобывающей промышленности.</p>',
            content_kz: '<p class="mb-5">RFID технологиясы тау-кен өнеркәсібіндегі операцияларда төңкеріс жасады. RFID тегтерін қолдану арқылы компаниялар активтердің кең ауқымын, соның ішінде жабдықтарды, құралдарды және көліктерді тиімді бақылап, басқара алады, олардың орны мен күйі нақты уақытта белгілі болуын қамтамасыз етеді. Бұл технология сонымен қатар инвентарлық қорларды, әсіресе қосалқы бөлшектер мен шығын материалдарын басқаруды жеңілдетеді. Персонал RFID бейджиктерімен жабдықталуы мүмкін, бұл тау-кен өндірісі объектілерінде орналасқан жерді дәл бақылауға мүмкіндік береді, бұл қауіпсіздік шаралары мен төтенше жағдайларды жою мүмкіндіктерін арттырады. RFID жеткізу тізбегі мен логистикада маңызды рөл атқарады, материалдардың өндіруден өңдеуге дейінгі қозғалысын реттейді. Ол сондай-ақ техникалық қызмет көрсету мен тексерулерді жоспарлауда маңызды рөл атқарады, жабдықтың қауіпсіздік стандарттарына сәйкестігіне кепілдік береді. RFID енгізу стратегиялық жоспарлауды және тұрақты басқаруды талап етеді, бірақ оның қауіпсіздік, тиімділік және сәйкестік бойынша артықшылықтары тау-кен өнеркәсібі үшін баға жетпес құнды болып табылады.</p>',
            content_en: '<p class="mb-5">RFID technology has revolutionized operations in the mining industry. By employing RFID tags, companies can effectively track and manage a wide array of assets, including equipment, tools, and vehicles, ensuring their location and status are known in real-time. This technology also streamlines inventory management, particularly for spare parts and consumables. Personnel can be equipped with RFID badges, enabling precise location tracking within mining facilities, which enhances safety measures and emergency response capabilities. RFID plays a vital role in supply chain and logistics, regulating the movement of materials from extraction to processing. It is also instrumental in scheduling maintenance and inspections, guaranteeing equipment compliance with safety standards. Implementing RFID requires strategic planning and ongoing management, but its benefits in terms of safety, efficiency, and compliance are invaluable to the mining industry.</p>',
            works: []
        }, {
            id: 3,
            title: "Транспорт и логистика",
            title_kz: "Көлік және логистика",
            title_en: "Transport and Logistics",
            description: "Технология RFID стала незаменимым инструментом в транспортно-логистическом секторе. Оно обеспечивает точное отслеживание и управление активами, включая товары, транспортные средства и контейнеры, обеспечивая легкий доступ к их местонахождению и статусу в режиме реального времени. Эта технология упрощает управление запасами, предоставляя точные данные об уровне запасов и улучшая процессы выполнения заказов. RFID-метки используются для идентификации и контроля отдельных предметов в поставках, повышая прозрачность и уменьшая количество ошибок в цепочке поставок. Кроме того, персонал может быть оснащен бейджами RFID, позволяющими эффективно отслеживать сотрудников, что помогает контролировать рабочее время и обеспечивать соблюдение протоколов безопасности. Кроме того, технология RFID облегчает автоматический сбор данных для целей отчетности, анализа и обеспечения соответствия, оптимизации операций и принятие решений. Его реализация требует тщательного планирования и постоянного управления, но преимущества с точки зрения эффективности, точности и безопасности неоценимы для транспортно-логистической отрасли.",
            description_kz: "RFID технологиясы көлік және логистика секторында таптырмас құралға айналды. Ол активтерді, соның ішінде тауарларды, көліктерді және контейнерлерді нақты бақылауға және басқаруға мүмкіндік береді, олардың нақты уақыттағы орналасқан жері мен күйіне оңай қол жеткізуді қамтамасыз етеді. Бұл технология тауарлық-материалдық қорларды басқаруды оңтайландырады, қор деңгейлері туралы нақты деректерді қамтамасыз етеді және тапсырыстарды орындау процестерін жақсартады. RFID тегтері жеткізілімдердегі жеке элементтерді анықтау және бақылау, көрінуді жақсарту және жеткізу тізбегіндегі қателерді азайту үшін қолданылады. Сонымен қатар, қызметкерлер жұмыс уақытын бақылауға және қауіпсіздік хаттамаларының сақталуын қамтамасыз етуге көмектесетін қызметкерлерді тиімді қадағалауға мүмкіндік беретін RFID бейдждерімен жабдықталуы мүмкін. Сонымен қатар, RFID технологиясы есеп беру, талдау және сәйкестік мақсаттары үшін деректерді автоматтандырылған түсіруді жеңілдетеді, операцияларды оңтайландырады және шешім қабылдау. Оны жүзеге асыру мұқият жоспарлауды және тұрақты басқаруды талап етеді, бірақ тиімділік, дәлдік және қауіпсіздік тұрғысынан артықшылықтар көлік және логистика саласы үшін баға жетпес құнды болып табылады.",
            description_en: "RFID technology has become an indispensable tool in the transportation and logistics sector. It enables precise tracking and management of assets, including goods, vehicles, and containers, ensuring their real-time location and status are readily accessible. This technology streamlines inventory management, providing accurate data on stock levels and improving order fulfillment processes. RFID tags are used to identify and monitor individual items within shipments, enhancing visibility and reducing errors in the supply chain. Additionally, personnel can be equipped with RFID badges, allowing for efficient tracking of employees, which aids in monitoring work hours and ensuring compliance with safety protocols.Moreover, RFID technology facilitates automated data capture for reporting, analysis, and compliance purposes, optimizing operations and decision-making. Its implementation requires careful planning and ongoing management, but the benefits in terms of efficiency, accuracy, and security are invaluable to the transportation and logistics industry.\n",
            img: imgInds3,
            content: '<p class="mb-5">Технология RFID стала незаменимым инструментом в секторе транспорта и логистики. Оно обеспечивает точное отслеживание и управление активами, включая товары, транспортные средства и контейнеры, обеспечивая легкий доступ к их местонахождению и статусу в режиме реального времени. Эта технология упрощает управление запасами, предоставляя точные данные об уровне запасов и улучшая процессы выполнения заказов. RFID-метки используются для идентификации и контроля отдельных предметов в поставках, повышая прозрачность и уменьшая количество ошибок в цепочке поставок. Кроме того, персонал может быть оснащен бейджами RFID, позволяющими эффективно отслеживать сотрудников, что помогает контролировать рабочее время и обеспечивать соблюдение протоколов безопасности.Кроме того, технология RFID облегчает автоматический сбор данных для целей отчетности, анализа и соблюдения требований, оптимизации операций и принятие решений. Его реализация требует тщательного планирования и постоянного управления, но преимущества с точки зрения эффективности, точности и безопасности неоценимы для транспортно-логистической отрасли.</p>',
            content_kz: '<p class="mb-5">RFID технологиясы көлік және логистика секторында таптырмас құралға айналды. Ол активтерді, соның ішінде тауарларды, көліктерді және контейнерлерді нақты бақылауға және басқаруға мүмкіндік береді, олардың нақты уақыттағы орналасқан жері мен күйіне оңай қол жеткізуді қамтамасыз етеді. Бұл технология тауарлық-материалдық қорларды басқаруды оңтайландырады, қор деңгейлері туралы нақты деректерді қамтамасыз етеді және тапсырыстарды орындау процестерін жақсартады. RFID тегтері жеткізілімдердегі жеке элементтерді анықтау және бақылау, көрінуді жақсарту және жеткізу тізбегіндегі қателерді азайту үшін қолданылады. Сонымен қатар, қызметкерлер жұмыс уақытын бақылауға және қауіпсіздік хаттамаларының сақталуын қамтамасыз етуге көмектесетін қызметкерлерді тиімді қадағалауға мүмкіндік беретін RFID бейдждерімен жабдықталуы мүмкін. Сонымен қатар, RFID технологиясы есеп беру, талдау және сәйкестік мақсаттары үшін деректерді автоматтандырылған түсіруді жеңілдетеді, операцияларды оңтайландырады және шешім қабылдау Оны жүзеге асыру мұқият жоспарлауды және үздіксіз басқаруды талап етеді, бірақ тиімділік, дәлдік және қауіпсіздік тұрғысынан артықшылықтар көлік және логистика саласы үшін баға жетпес.</p>',
            content_en: '<p class="mb-5">RFID technology has become an indispensable tool in the transportation and logistics sector. It enables precise tracking and management of assets, including goods, vehicles, and containers, ensuring their real-time location and status are readily accessible. This technology streamlines inventory management, providing accurate data on stock levels and improving order fulfillment processes. RFID tags are used to identify and monitor individual items within shipments, enhancing visibility and reducing errors in the supply chain. Additionally, personnel can be equipped with RFID badges, allowing for efficient tracking of employees, which aids in monitoring work hours and ensuring compliance with safety protocols.Moreover, RFID technology facilitates automated data capture for reporting, analysis, and compliance purposes, optimizing operations and decision-making. Its implementation requires careful planning and ongoing management, but the benefits in terms of efficiency, accuracy, and security are invaluable to the transportation and logistics industry.</p>',
            works: [part3, part11, part6]
        }, {
            id: 4,
            title: "Розничная торговля и гостиничный бизнес",
            title_kz: "Бөлшек сауда және қонақжайлылық",
            title_en: "Retail and Hospitality",
            description: "Технология RFID произвела революцию в сфере розничной торговли и гостиничного бизнеса. Используя RFID-метки, предприятия могут эффективно отслеживать и управлять своими запасами, от одежды и потребительских товаров до постельного белья и предметов личной гигиены, обеспечивая точный контроль над уровнем запасов и минимизируя потери из-за усадки. Эта технология упрощает процесс оформления заказа, обеспечивая более быстрые и точные транзакции, что в конечном итоге повышает удовлетворенность клиентов. RFID-метки можно прикреплять к отдельным товарам, что позволяет розничным продавцам отслеживать перемещение товаров, оптимизировать выкладку на полках. В гостиничном секторе RFID-карты изменили управление ключами, обеспечив безопасный доступ к номерам и удобствам для гостей. Это не только повышает безопасность, но и улучшает общее впечатление гостя. Кроме того, технология RFID используется для идентификации персонала и учета рабочего времени, оптимизации организации труда и обеспечения соблюдения трудового законодательства. Более того, RFID облегчает сбор данных для отчетности, анализа и управления взаимоотношениями с клиентами, позволяя предприятиям принимать обоснованные решения и предоставлять индивидуальный опыт. Хотя внедрение RFID требует стратегического планирования и постоянного управления, его преимущества с точки зрения операционной эффективности, удовлетворенности клиентов и безопасности неоценимы для предприятий розничной торговли и гостиничного бизнеса.",
            description_kz: "RFID технологиясы бөлшек сауда және қонақжайлылық салаларындағы операцияларда төңкеріс жасады. RFID тегтерін қолдана отырып, кәсіпорындар киім-кешек пен тұтыну тауарларынан бастап, төсек-орын және тұрмыстық бұйымдарға дейін қорларды тиімді бақылап, басқара алады, қор деңгейін дәл бақылауды қамтамасыз етеді және қысқарудан болатын шығындарды азайтады. Бұл технология тезірек және дәлірек транзакцияларды жүргізуге мүмкіндік беретін, сайып келгенде, тұтынушылардың қанағаттануын жақсарта отырып, шығу процесін жеңілдетеді. RFID тегтерін жеке элементтерге бекітуге болады, бұл бөлшек саудагерлерге өнімнің қозғалысын бақылауға, сөре дисплейлерін оңтайландыруға мүмкіндік береді. Қонақжайлылық секторында RFID карталары қонақ бөлмелері мен ыңғайлылыққа қауіпсіз қол жеткізуді қамтамасыз ететін негізгі басқаруды өзгертті. Бұл қауіпсіздікті арттырып қана қоймайды, сонымен қатар қонақтардың жалпы тәжірибесін жақсартады. Сонымен қатар, RFID технологиясы қызметкерлерді сәйкестендіру және уақытты бақылау, еңбекті басқаруды оңтайландыру және еңбек ережелерінің сақталуын қамтамасыз ету үшін қолданылады. Сонымен қатар, RFID есеп беру, талдау және тұтынушылармен қарым-қатынасты басқару үшін деректерді жинауды жеңілдетеді, бұл бизнеске негізделген шешімдер қабылдауға және бейімделген тәжірибені қамтамасыз етуге мүмкіндік береді. RFID енгізу стратегиялық жоспарлауды және тұрақты басқаруды қажет еткенімен, оның операциялық тиімділік, тұтынушылардың қанағаттанушылығы және қауіпсіздік тұрғысынан артықшылықтары бөлшек сауда және қонақжайлылық индустриясы үшін баға жетпес құнды болып табылады.",
            description_en: "RFID technology has revolutionized operations in the retail and hospitality industries. By leveraging RFID tags, businesses can efficiently track and manage their inventory, from clothing and consumer goods to linens and amenities, ensuring precise control over stock levels and minimizing losses due to shrinkage. This technology streamlines the check-out process, allowing for faster and more accurate transactions, ultimately improving customer satisfaction. RFID tags can be attached to individual items, enabling retailers to monitor product movement, optimize shelf displays.. In the hospitality sector, RFID cards have transformed key management, providing secure access to guest rooms and amenities. This not only enhances security but also improves the overall guest experience. Additionally, RFID technology is employed for staff identification and time tracking, streamlining labor management and ensuring compliance with labor regulations. Moreover, RFID facilitates data capture for reporting, analysis, and customer relationship management, enabling businesses to make informed decisions and provide tailored experiences. While the implementation of RFID requires strategic planning and ongoing management, its benefits in terms of operational efficiency, customer satisfaction, and security are invaluable to the retail and hospitality industries.",
            img: imgInds4,
            content: '<p class="mb-5">Технология RFID произвела революцию в сфере розничной торговли и гостиничного бизнеса. Используя RFID-метки, предприятия могут эффективно отслеживать и управлять своими запасами, от одежды и потребительских товаров до постельного белья и предметов личной гигиены, обеспечивая точный контроль над уровнем запасов и минимизируя потери из-за усадки. Эта технология упрощает процесс оформления заказа, обеспечивая более быстрые и точные транзакции, что в конечном итоге повышает удовлетворенность клиентов. RFID-метки можно прикреплять к отдельным товарам, что позволяет розничным продавцам отслеживать перемещение товаров, оптимизировать выкладку на полках. В гостиничном секторе RFID-карты изменили управление ключами, обеспечив безопасный доступ к номерам и удобствам для гостей. Это не только повышает безопасность, но и улучшает общее впечатление гостя. Кроме того, технология RFID используется для идентификации персонала и учета рабочего времени, оптимизации организации труда и обеспечения соблюдения трудового законодательства. Более того, RFID облегчает сбор данных для отчетности, анализа и управления взаимоотношениями с клиентами, позволяя предприятиям принимать обоснованные решения и предоставлять индивидуальный опыт. Хотя внедрение RFID требует стратегического планирования и постоянного управления, его преимущества с точки зрения операционной эффективности, удовлетворенности клиентов и безопасности неоценимы для предприятий розничной торговли и гостиничного бизнеса.</p>',
            content_kz: '<p class="mb-5">RFID технологиясы бөлшек сауда және қонақжайлылық салаларындағы операцияларда төңкеріс жасады. RFID тегтерін қолдана отырып, кәсіпорындар киім-кешек пен тұтыну тауарларынан бастап, төсек-орын және тұрмыстық бұйымдарға дейін қорларды тиімді бақылап, басқара алады, қор деңгейін дәл бақылауды қамтамасыз етеді және қысқарудан болатын шығындарды азайтады. Бұл технология тезірек және дәлірек транзакцияларды жүргізуге мүмкіндік беретін, сайып келгенде, тұтынушылардың қанағаттануын жақсарта отырып, шығу процесін жеңілдетеді. RFID тегтерін жеке элементтерге бекітуге болады, бұл бөлшек саудагерлерге өнімнің қозғалысын бақылауға, сөре дисплейлерін оңтайландыруға мүмкіндік береді. Қонақжайлылық секторында RFID карталары қонақ бөлмелері мен ыңғайлылыққа қауіпсіз қол жеткізуді қамтамасыз ететін негізгі басқаруды өзгертті. Бұл қауіпсіздікті арттырып қана қоймайды, сонымен қатар қонақтардың жалпы тәжірибесін жақсартады. Сонымен қатар, RFID технологиясы қызметкерлерді сәйкестендіру және уақытты бақылау, еңбекті басқаруды оңтайландыру және еңбек ережелерінің сақталуын қамтамасыз ету үшін қолданылады. Сонымен қатар, RFID есеп беру, талдау және тұтынушылармен қарым-қатынасты басқару үшін деректерді жинауды жеңілдетеді, бұл бизнеске негізделген шешімдер қабылдауға және бейімделген тәжірибені қамтамасыз етуге мүмкіндік береді. RFID енгізу стратегиялық жоспарлауды және тұрақты басқаруды қажет етсе де, оның операциялық тиімділік, тұтынушылардың қанағаттануы және қауіпсіздік тұрғысынан артықшылықтары бөлшек сауда және қонақжайлылық индустриясы үшін баға жетпес құнды болып табылады.</p>',
            content_en: '<p class="mb-5">RFID technology has revolutionized operations in the retail and hospitality industries. By leveraging RFID tags, businesses can efficiently track and manage their inventory, from clothing and consumer goods to linens and amenities, ensuring precise control over stock levels and minimizing losses due to shrinkage. This technology streamlines the check-out process, allowing for faster and more accurate transactions, ultimately improving customer satisfaction. RFID tags can be attached to individual items, enabling retailers to monitor product movement, optimize shelf displays.. In the hospitality sector, RFID cards have transformed key management, providing secure access to guest rooms and amenities. This not only enhances security but also improves the overall guest experience. Additionally, RFID technology is employed for staff identification and time tracking, streamlining labor management and ensuring compliance with labor regulations. Moreover, RFID facilitates data capture for reporting, analysis, and customer relationship management, enabling businesses to make informed decisions and provide tailored experiences. While the implementation of RFID requires strategic planning and ongoing management, its benefits in terms of operational efficiency, customer satisfaction, and security are invaluable to the retail and hospitality industries.</p>',
            works: [part12, part5]
        }], locations: [{
            id: 1, name: "Алматы", name_kz: "Алматы", name_en: "Almaty", addresses: [{
                address: "050052, г. Алматы, микрорайон Таугуль, улица Мустай Карим, д.13а, офис 240",
                address_kz: "050052, Алматы, Таугүл шағын ауданы, Мұстай Кәрім көшесі, 13а, 240 каб.",
                address_en: "050052, Almaty, Taugul microdistrict, Mustai Karim street, 13a, office 240",
                phone: "+7 (771) 762-22-85",
                map: "<iframe src=\"https://yandex.ru/map-widget/v1/?um=constructor%3Ab608545a9131312c3b29a42631b1d2c452ff7cfe18235f389181997e98526fea&amp;source=constructor\" width=\"100%\" height=\"574\" frameborder=\"0\"></iframe>"
            }]
        }, {
            id: 2, name: "Астана", name_kz: "Астана", name_en: "Astana", addresses: [{
                address: "050052, г. Алматы, микрорайон Таугуль, улица Мустай Карим, д.13а, офис 240",
                address_kz: "050052, Алматы, Таугүл шағын ауданы, Мұстай Кәрім көшесі, 13а, 240 каб.",
                address_en: "050052, Almaty, Taugul microdistrict, Mustai Karim street, 13a, office 240",
                phone: "+7 (771) 762-22-85",
                map: "<iframe src=\"https://yandex.ru/map-widget/v1/?um=constructor%3Ab608545a9131312c3b29a42631b1d2c452ff7cfe18235f389181997e98526fea&amp;source=constructor\" width=\"100%\" height=\"574\" frameborder=\"0\"></iframe>"
            }]
        }, {
            id: 3, name: "Ташкент", name_kz: "Ташкент", name_en: "Tashkent", addresses: [{
                address: "050052, г. Алматы, микрорайон Таугуль, улица Мустай Карим, д.13а, офис 240",
                address_kz: "050052, Алматы, Таугүл шағын ауданы, Мұстай Кәрім көшесі, 13а, 240 каб.",
                address_en: "050052, Almaty, Taugul microdistrict, Mustai Karim street, 13a, office 240",
                phone: "+7 (771) 762-22-85",
                map: "<iframe src=\"https://yandex.ru/map-widget/v1/?um=constructor%3Ab608545a9131312c3b29a42631b1d2c452ff7cfe18235f389181997e98526fea&amp;source=constructor\" width=\"100%\" height=\"574\" frameborder=\"0\"></iframe>"
            }]
        }, {
            id: 4, name: "Абу-Даби", name_kz: "Абу-Даби", name_en: "Abu-Dhabi", addresses: [{
                address: "050052, г. Алматы, микрорайон Таугуль, улица Мустай Карим, д.13а, офис 240",
                address_kz: "050052, Алматы, Таугүл шағын ауданы, Мұстай Кәрім көшесі, 13а, 240 каб.",
                address_en: "050052, Almaty, Taugul microdistrict, Mustai Karim street, 13a, office 240",
                phone: "+7 (771) 762-22-85",
                map: "<iframe src=\"https://yandex.ru/map-widget/v1/?um=constructor%3Ab608545a9131312c3b29a42631b1d2c452ff7cfe18235f389181997e98526fea&amp;source=constructor\" width=\"100%\" height=\"574\" frameborder=\"0\"></iframe>"
            }]
        }], products: [{
            id: 1,
            title: "АСКОУ – ИНВЕНТАРИЗАЦИЯ",
            title_kz: "ASCOU – ИНВЕНТОРЛЫҚ",
            title_en: "ASCOA - INVENTORY",
            description: "ASCOA - Inventory» — комплексное решение, предназначенное для обеспечения тщательной инвентаризации активов, включая товарно-материальные запасы, основные средства и другие ресурсы внутри предприятия. Разработка данной системы была обусловлена острой необходимостью точного учета и управления объектами в различных организационных структурах. \"ASCOA - Inventory\" предлагает целостное представление об активах организации и их количествах в различных подразделениях, а также ведет подробную историю жизненного цикла каждого объекта - от приобретения до утилизации. Помимо стандартного управления запасами Система обладает расширенными функциями, позволяющими отслеживать физическое перемещение активов и накладывать ограничения на их вывоз из определенных мест, таких как офисы или организационные помещения.Кроме того, она тщательно регистрирует вход и выход контролируемых активов.Кроме того, «ASCOA - Inventory» предлагает возможность связывать активы с конкретными местоположениями, повышая точность управления и отслеживания активов.",
            description_kz: "ASCOA - Инвентаризация» бұл кәсіпорын ішіндегі қорларды, негізгі құралдарды және басқа ресурстарды қоса алғанда, активтерді мұқият түгендеуді қамтамасыз етуге арналған кешенді шешім. Бұл жүйенің дамуы әртүрлі ұйымдық құрылымдардағы объектілерді дәл есепке алу және басқарудың маңызды қажеттілігінен туындады. Әкімшілік кеңселерден өндірістік нысандарға дейінгі баптаулар.\"ASCOA - Инвентарлық\" ұйымның активтері мен олардың әртүрлі бөлімшелердегі санының тұтас көрінісін ұсынады, сонымен қатар әрбір нысанның өмірлік циклінің егжей-тегжейлі тарихын сақтайды - сатып алудан шығаруға дейін. Стандартты инвентарлық басқарудан тыс. , жүйе активтердің физикалық қозғалысын бақылауға және оларды кеңселер немесе ұйымдық үй-жайлар сияқты белгіленген аумақтардан шығаруға шектеулер енгізуге мүмкіндік беретін жетілдірілген мүмкіндіктерге ие.Сонымен қатар, ол бақыланатын активтердің кіруі мен шығуын мұқият журналдайды. «ASCOA - түгендеу» активтерді басқару мен қадағалаудағы дәлдікті арттыра отырып, белгілі бір орындармен активтерді байланыстыру мүмкіндігін ұсынады.",
            description_en: "ASCOA - Inventory\" is a comprehensive solution designed to provide a thorough inventory of assets, including inventory, fixed assets, and other resources within an enterprise. The development of this system was driven by the critical need to accurately record and manage objects in various organisational settings, spanning from administrative offices to manufacturing facilities. \"ASCOA - Inventory\" offers a holistic view of the organisation's assets and their quantities across different divisions, while also maintaining a detailed history of each object's lifecycle - from acquisition to disposal. Beyond standard inventory management, the system boasts advanced features, allowing for the monitoring of physical movements of assets and the imposition of restrictions on their removal from designated areas, such as offices or organisational premises. Additionally, it meticulously logs the entry and exit of controlled assets. Moreover, \"ASCOA - Inventory\" offers the capability to associate assets with specific locations, enhancing precision in asset management and tracking.",
            img: imgProd1,
            certificates: [{
                id: 1, name: "ASCOA - INVENTORY", file: prodPDF1
            }]
        }, {
            id: 2,
            title: "АСКОУ – СКЛАД",
            title_kz: "ASCOU – ҚОЙМА",
            title_en: "ASCOU – WAREHOUSE",
            description: "ASCOA – Склад» — это сложная система, предназначенная для учета, управления запасами и точного отслеживания товарно-материальных запасов на огромных складских объектах. На крупных производственных предприятиях, где на складах хранятся тысячи, а часто и десятки тысяч отдельных товаров, каждый из них Кроме того, может охватывать множество отдельных объектов запасов, товаров и материалов. Традиционно проведение инвентаризации такого обширного набора предметов представляет собой трудоемкую работу, часто занимающую несколько месяцев и преимущественно выполняемую вручную. Ускорить эту операцию почти до за один день или даже часы, одновременно обеспечивая прозрачность и автоматизацию, был разработан комплекс «АСКОА-Склад».Благодаря интеграции технологии RFID «АСКОА-Склад» обеспечивает быструю инвентаризацию, оприходование и выдачу товарно-материальных ценностей, обеспечивая при этом бесшовную совместимость. с существующей учетной и финансовой системами предприятия.Такая интеграция оптимизирует операции, повышает точность и существенно ускоряет общий процесс управления запасами.",
            description_kz: "ASCOA – қойма» – бұл кең қоймалардағы тауарлық-материалдық қорларды есепке алуға, басқаруға және дәл қадағалауға арналған күрделі жүйе. Қоймаларда мыңдаған, көбінесе он мыңдаған әртүрлі заттар бар ірі өндірістік кәсіпорындарда олардың әрқайсысында бұдан әрі көптеген жекелеген инвентарлық объектілерді, тауарларды және материалдарды қамтуы мүмкін.Дәстүрлі түрде заттардың мұндай кең ауқымын түгендеу көп уақытты қажет ететін жұмыс, көбінесе бірнеше айға созылады және негізінен қолмен орындалатын процестерге байланысты. Бұл операцияны тездету үшін шамамен бір күн немесе тіпті сағат, бір мезгілде ашықтық пен автоматтандыруды қамтамасыз ете отырып, ASCOA-Warehouse кешені әзірленді.RFID технологиясының интеграциясы арқылы «ASCOA - қойма» тауарлық-материалдық құндылықтарды жылдам түгендеуді, капиталдандыруды және шығаруды жеңілдетеді, сонымен бірге үздіксіз үйлесімділікті ұсынады. кәсіпорынның қолданыстағы бухгалтерлік және қаржылық жүйелерімен.Бұл интеграция операцияларды оңтайландырады, дәлдікті арттырады және жалпы қорларды басқару процесін айтарлықтай жылдамдатады.",
            description_en: "ASCOA – Warehouse\" is a sophisticated system tailored for the accounting, inventory management, and precise tracking of inventory items within vast warehouse facilities. In sizeable manufacturing enterprises, where warehouses house thousands, and often tens of thousands, of distinct items, each of these may further encompass numerous individual objects of inventory, goods, and materials. Traditionally, conducting inventory for such an extensive array of items is a time-consuming endeavour, often extending over several months and predominantly reliant on manual processes. To expedite this operation to nearly one day or even hours, while simultaneously ensuring transparency and automation, the ASCOA-Warehouse complex was developed. Through the integration of RFID technology, \"ASCOA - Warehouse\" facilitates swift inventorying, capitalization, and issuance of inventory items, all while offering seamless compatibility with the existing accounting and financial systems of the enterprise. This integration streamlines operations, enhances accuracy, and significantly expedites the overall inventory management process.",
            img: imgProd2,
            certificates: [{
                id: 1, name: "ASCOA - WAREHOUSE", file: prodPDF2
            }]
        }, {
            id: 3,
            title: "АСКОУ – охрана труда и безопасность",
            title_kz: "АСКОУ – еңбекті қорғау және қауіпсіздік",
            title_en: "ASCOU – OCCUPATIONAL HEALTH AND SAFETY",
            description: "Модуль ASCOA по охране труда и технике безопасности предоставляет комплексную платформу для отслеживания и документирования учебных занятий по охране труда, а также позволяет легко управлять записями с помощью подписей и фотографий на мобильных устройствах. Эта универсальная система распространяется на медицинские осмотры и регистрацию сотрудников. Кроме того, система охраны труда на основе RFID обеспечивает отслеживание персонала в режиме реального времени, проверку защитного оборудования, отчеты об инцидентах и мониторинг соответствия требованиям. Хотя внедрение требует тщательного планирования, преимущества в области безопасности, соответствия требованиям и операционной эффективности делают его ценной инвестицией в благополучие на рабочем месте.",
            description_kz: "ASCOA Еңбекті қорғау және қауіпсіздік модулі мобильді құрылғылардағы қолтаңбалар мен фотосуреттер арқылы жазбаларды үздіксіз басқару, еңбекті қорғау бойынша оқу сабақтарын қадағалау және құжаттау үшін жан-жақты платформаны ұсынады. Бұл әмбебап жүйе медициналық тексерулер мен қызметкерлерді тіркеуді қамтиды. Сонымен қатар, RFID негізіндегі OHS жүйесі нақты уақыт режимінде персоналды қадағалауды, қауіпсіздік жабдығын тексеруді, оқиға туралы есеп беруді және сәйкестікті бақылауды ұсынады. Іске асыру мұқият жоспарлауды қажет еткенімен, қауіпсіздік, сәйкестік және операциялық тиімділіктегі артықшылықтар оны жұмыс орнының әл-ауқаты үшін құнды инвестицияға айналдырады.",
            description_en: "The ASCOA Occupational Health and Safety module provides a comprehensive platform for tracking and documenting OSH training sessions, seamlessly managing records through signatures and photos on mobile devices. This versatile system extends to include medical examinations and employee registration. Additionally, an RFID-based OHS system offers real-time personnel tracking, safety equipment verification, incident reporting, and compliance monitoring. While implementation requires careful planning, the benefits in safety, compliance, and operational efficiency make it a valuable investment for workplace well-being.",
            img: imgProd3,
            certificates: [{
                id: 1, name: "ASCOA - OCCUPATIONAL HEALTH AND SAFETY", file: prodPDF3
            }]
        }, {
            id: 4,
            title: "АСКОУ – ТЕХНИЧЕСКОЕ ОБСЛУЖИВАНИЕ И РЕМОНТ",
            title_kz: "ASCOU – ҚЫЗМЕТ КӨРСЕТУ ЖӘНЕ ЖӨНДЕУ",
            title_en: "ASCOU – MAINTENANCE AND REPAIR",
            description: "Система технического обслуживания и ремонта ASCOA обеспечивает бесперебойную работу инфраструктуры и оборудования, особенно на крупных, географически рассредоточенных предприятиях. Автоматизированное планирование и выполнение технического обслуживания, а также тщательный оперативный учет играют решающую роль в обеспечении оптимальной производительности. Это особенно важно, когда оборудование отвечает за соблюдение стандартов безопасности на транспорте, например, в поездах и самолетах. Интегрируя передовые системы, такие как ASCOA – техническое обслуживание и ремонт, компании могут осуществлять контроль в режиме реального времени над плановыми задачами по техническому обслуживанию, независимо от отраслевой специфики. Кроме того, возможность собирать и анализировать данные об операционных расхождениях позволяет предприятиям активно решать проблемы и принимать специализированные меры по снижению сбоев и отказов оборудования.",
            description_kz: "ASCOA техникалық қызмет көрсету және жөндеу жүйесі инфрақұрылым мен жабдықтардың, әсіресе ірі, географиялық тұрғыдан шашыраңқы кәсіпорындар үшін үздіксіз жұмыс істеуін қамтамасыз етеді. Техникалық қызмет көрсетуді автоматтандырылған жоспарлау және орындау, мұқият операциялық есеппен қатар, оңтайлы өнімділікті қамтамасыз етуде шешуші рөл атқарады. Бұл әсіресе жабдыққа пойыздар мен ұшақтар сияқты тасымалдаудағы қауіпсіздік стандарттарын сақтау міндеті қойылған кезде өте маңызды. ASCOA - техникалық қызмет көрсету және жөндеу сияқты озық жүйелерді біріктіру арқылы компаниялар салалық ерекшеліктерге қарамастан жоспарланған техникалық қызмет көрсету тапсырмаларын нақты уақытта бақылауды жүзеге асыра алады. Сонымен қатар, операциялық сәйкессіздіктер туралы деректерді жинау және талдау мүмкіндігі бизнеске мәселелерді белсенді түрде шешуге және жабдықтың ақаулары мен ақауларын азайту үшін арнайы шараларды жүзеге асыруға мүмкіндік береді.",
            description_en: "ASCOA maintenance and repair system ensures seamless functioning of infrastructure and equipment, particularly for large, geographically dispersed enterprises. The automated planning and execution of maintenance, along with diligent operational accounting, play a pivotal role in ensuring optimal performance. This is especially crucial when equipment is tasked with upholding safety standards in transportation, such as for trains and planes. By integrating advanced systems, like ASCOA - maintenance and repair, companies can exercise real-time control over planned maintenance tasks, regardless of industry specifics. Additionally, the ability to collect and analyse data on operational discrepancies empowers businesses to proactively address issues and implement specialised measures to reduce equipment malfunctions and failures.",
            img: imgProd4,
            certificates: [{
                id: 1, name: "ASCOA - MAINTENANCE AND REPAIR", file: prodPDF4
            }]
        },]
    }, getters: {
        getNews: (state) => state.news,
        getAccomplishments: (state) => state.accomplishments,
        getIndSectors: (state) => state.indSectors,
        getLocations: (state) => state.locations,
        getProducts: (state) => state.products
    },
});
